/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as StartRouteImport } from './routes/start'
import { Route as AdminTeamIdRouteImport } from './routes/admin.$teamId'
import { Route as CheckoutTeamIdRouteImport } from './routes/checkout.$teamId'
import { Route as PreviewTeamIdRouteImport } from './routes/preview.$teamId'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicManifestSlugRouteImport } from './routes/api/public/manifest.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamIdRoute = AdminTeamIdRouteImport.update({
  id: '/admin/$teamId',
  path: '/admin/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutTeamIdRoute = CheckoutTeamIdRouteImport.update({
  id: '/checkout/$teamId',
  path: '/checkout/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewTeamIdRoute = PreviewTeamIdRouteImport.update({
  id: '/preview/$teamId',
  path: '/preview/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicManifestSlugRoute = ApiPublicManifestSlugRouteImport.update({
  id: '/api/public/manifest/$slug',
  path: '/api/public/manifest/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/start': typeof StartRoute
  '/admin/$teamId': typeof AdminTeamIdRoute
  '/checkout/$teamId': typeof CheckoutTeamIdRoute
  '/preview/$teamId': typeof PreviewTeamIdRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/manifest/$slug': typeof ApiPublicManifestSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/start': typeof StartRoute
  '/admin/$teamId': typeof AdminTeamIdRoute
  '/checkout/$teamId': typeof CheckoutTeamIdRoute
  '/preview/$teamId': typeof PreviewTeamIdRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/manifest/$slug': typeof ApiPublicManifestSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/start': typeof StartRoute
  '/admin/$teamId': typeof AdminTeamIdRoute
  '/checkout/$teamId': typeof CheckoutTeamIdRoute
  '/preview/$teamId': typeof PreviewTeamIdRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/manifest/$slug': typeof ApiPublicManifestSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/auth'
    | '/dashboard'
    | '/start'
    | '/admin/$teamId'
    | '/checkout/$teamId'
    | '/preview/$teamId'
    | '/api/public/stripe-webhook'
    | '/api/public/manifest/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/auth'
    | '/dashboard'
    | '/start'
    | '/admin/$teamId'
    | '/checkout/$teamId'
    | '/preview/$teamId'
    | '/api/public/stripe-webhook'
    | '/api/public/manifest/$slug'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/auth'
    | '/dashboard'
    | '/start'
    | '/admin/$teamId'
    | '/checkout/$teamId'
    | '/preview/$teamId'
    | '/api/public/stripe-webhook'
    | '/api/public/manifest/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  StartRoute: typeof StartRoute
  AdminTeamIdRoute: typeof AdminTeamIdRoute
  CheckoutTeamIdRoute: typeof CheckoutTeamIdRoute
  PreviewTeamIdRoute: typeof PreviewTeamIdRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicManifestSlugRoute: typeof ApiPublicManifestSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$teamId': {
      id: '/admin/$teamId'
      path: '/admin/$teamId'
      fullPath: '/admin/$teamId'
      preLoaderRoute: typeof AdminTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$teamId': {
      id: '/checkout/$teamId'
      path: '/checkout/$teamId'
      fullPath: '/checkout/$teamId'
      preLoaderRoute: typeof CheckoutTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$teamId': {
      id: '/preview/$teamId'
      path: '/preview/$teamId'
      fullPath: '/preview/$teamId'
      preLoaderRoute: typeof PreviewTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/manifest/$slug': {
      id: '/api/public/manifest/$slug'
      path: '/api/public/manifest/$slug'
      fullPath: '/api/public/manifest/$slug'
      preLoaderRoute: typeof ApiPublicManifestSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  StartRoute: StartRoute,
  AdminTeamIdRoute: AdminTeamIdRoute,
  CheckoutTeamIdRoute: CheckoutTeamIdRoute,
  PreviewTeamIdRoute: PreviewTeamIdRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicManifestSlugRoute: ApiPublicManifestSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
